### ISSUE TITLE
Uncaught Error: This buffer's content is too large to fit into a string.Consider using APIs lik...

### ISSUE THREAD

**Issue by juhenriquez** [KunihikoKido/atom-json-converter#8]
Select a Large CSV file approx. 300mb try to convert. Voila!

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [json-converter](https://github.com/KunihikoKido/atom-json-converter) package 0.2.4

### Stack Trace

Uncaught Error: This buffer's content is too large to fit into a string.

Consider using APIs like `getTextInRange` to access the data you need.

```
At C:\Users\julia\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

Error: This buffer's content is too large to fit into a string.

Consider using APIs like `getTextInRange` to access the data you need.
    at TextBuffer.getText (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:486046)
    at TextEditor.getText (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:12850)
    at Object.csvToJson (/packages/json-converter/lib/json-converter.coffee:114:18)
    at /packages/json-converter/lib/json-converter.coffee:100:94)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:671034)
    at EventEmitter.t (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:678418)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -3:14 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:10.7.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:47.8.0 find-and-replace:show (input.hidden-input)
     -0:46.1.0 core:paste (input.hidden-input)
     -0:45.4.0 core:undo (input.hidden-input)
     -0:27.5.0 json-converter:csv-to-json (input.hidden-input)
```

### Non-Core Packages

```
json-converter 0.2.4 
```

**Comment by systamper** [comment]
Guessing it is related. I am trying to open a large(ish) csv of around 250 megs (1.6m lines). Every 30 seconds or so, I get an error saying the application is not responding. I've tried waiting many times,, but nothing ever happens. Is there a work around?
